app:
    name: Trabajo
server:
    contextPath: /monitorizacion
url.indexado: http://localhost:9200/pruebas/medicion
url.busqueda: http://localhost:9200/pruebas/medicion/_search
url.busqueda.medida: http://localhost:9200/pruebas/medicion/
url.indice: http://localhost:9200/pruebas