app:
    name: Monitorizacion
server:
    contextPath: /monitorizacion
url.indexado: http://localhost:9200/domotica/medicion
url.busqueda: http://localhost:9200/domotica/medicion/_search
url.busqueda.medida: http://localhost:9200/domotica/medicion/
url.indice: http://localhost:9200/domotica

